# Generated by Django 6.0.4 on 2026-04-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('homeId', models.PositiveIntegerField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASIA_HAR_SERVER_CORE.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('patientsAssigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ASIA_HAR_SERVER_CORE.patient')),
            ],
        ),
    ]
