# Generated by Django 6.0.4 on 2026-05-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_default='username', max_length=100)),
                ('first_name', models.CharField(db_default='first_name', max_length=100)),
                ('last_name', models.CharField(db_default='last_name', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_default='password', max_length=256)),
                ('admin', models.BooleanField(db_default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_default='first_name', max_length=100)),
                ('last_name', models.CharField(db_default='last_name', max_length=100)),
                ('card_id', models.CharField(max_length=10, unique=True)),
                ('home_id', models.PositiveIntegerField()),
                ('sensor_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ASIA_HAR_SERVER_CORE.patientsensordata')),
                ('users_assigned', models.ManyToManyField(to='ASIA_HAR_SERVER_CORE.user')),
            ],
        ),
    ]
