# Generated by Django 6.0.4 on 2026-05-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASIA_HAR_SERVER_CORE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
