# Generated by Django 6.0.4 on 2026-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASIA_HAR_SERVER_CORE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientData',
            new_name='PatientSensorData',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='idCard',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='data',
            new_name='sensorData',
        ),
    ]
