# Generated by Django 6.0.4 on 2026-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASIA_HAR_SERVER_CORE', '0005_alter_patientsensordata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsensordata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
