# Generated by Django 6.0.4 on 2026-04-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASIA_HAR_SERVER_CORE', '0006_alter_patientsensordata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_default='last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_default='username', max_length=100),
        ),
    ]
