# Generated by Django 6.0.4 on 2026-04-29 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASIA_HAR_SERVER_CORE', '0007_user_first_name_user_last_name_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(db_default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(db_default='last_name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sensorData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ASIA_HAR_SERVER_CORE.patientsensordata'),
        ),
    ]
